/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#313030",
        "on-secondary-fixed": "#131f00",
        "surface-bright": "#3a3939",
        "on-secondary": "#243600",
        "surface-container": "#201f1f",
        "tertiary-container": "#b8b6b5",
        "outline-variant": "#524534",
        "primary-container": "#f5a623",
        "primary-fixed-dim": "#ffb955",
        error: "#ffb4ab",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        background: "#131313",
        "surface-dim": "#131313",
        "tertiary-fixed": "#e5e2e1",
        "secondary-fixed": "#bcf54e",
        "primary-fixed": "#ffddb4",
        "on-tertiary-container": "#484747",
        "on-primary-container": "#644000",
        "inverse-on-surface": "#313030",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#d7c3ae",
        surface: "#131313",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#291800",
        "on-primary-fixed-variant": "#633f00",
        outline: "#9f8e7a",
        tertiary: "#d4d1d1",
        primary: "#ffc880",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#a1d732",
        "on-secondary-fixed-variant": "#364e00",
        "inverse-primary": "#835500",
        "surface-tint": "#ffb955",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        secondary: "#a1d732",
        "on-secondary-container": "#2d4200",
        "on-tertiary-fixed": "#1c1b1b",
        "secondary-container": "#82b500",
        "on-primary": "#452b00",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474746",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        header_height: "48px",
        sidebar_width: "220px",
        "container-padding": "24px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "display-lg": ["DM Serif Display"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["DM Serif Display"],
        "headline-md": ["DM Serif Display"],
        "data-lg": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "data-md": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            fontWeight: "400",
          },
        ],
        "display-lg-mobile": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "400",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            fontWeight: "400",
          },
        ],
        "data-lg": [
          "20px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "400",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.08em",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            fontWeight: "400",
          },
        ],
        "data-md": [
          "14px",
          {
            lineHeight: "18px",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
};
